CREATE TABLE cliente (
	id INT(10) PRIMARY KEY AUTO_INCREMENT,
	nome varchar(255) NOT NULL,
	data_cadastro TIMESTAMP NOT NULL,
	ativo SMALLINT(1) NOT NULL DEFAULT 0,
	cgccpf VARCHAR(14) NOT NULL,
	email varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;